version: '3'

services:

  mysql-davenpay:
    container_name: mysql-davenpay
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: davenpay
      MYSQL_ROOT_PASSWORD: davenpay
    networks:
      - network-davenpay

  redis-davenpay:
    container_name: redis-davenpay
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      MYSQL_DATABASE: davenpay
      MYSQL_ROOT_PASSWORD: davenpay
    networks:
      - network-davenpay

  instancia01:
    container_name: instancia01-davenpay
    build: .docker/instancia
    # stdin_open: true
    # tty: true
    # command: composer install
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/instancia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-davenpay
    depends_on:
      - "mysql-davenpay"
      - "redis-davenpay"

  instancia02:
    container_name: instancia02-davenpay
    build: .docker/instancia
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/instancia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-davenpay
    depends_on:
      - "mysql-davenpay"
      - "redis-davenpay"

  nginx-davenpay:
    build: .docker/nginx
    container_name: nginx-davenpay
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network-davenpay
    depends_on:
      - "instancia01"
      - "instancia02"

networks:
  network-davenpay:
    driver: bridge