version: '3'

services:

  site:
    container_name: site
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - default
    volumes:
      - "./site:/usr/share/nginx/html"

  mysql-davenpay:
    container_name: mysql-davenpay
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: davenpay
      MYSQL_ROOT_PASSWORD: davenpay
    networks:
      - default

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      MYSQL_DATABASE: davenpay
      MYSQL_ROOT_PASSWORD: davenpay
    networks:
      - default

  api01:
    container_name: api01
    build: .docker/instancia
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/instancia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - "mysql-davenpay"
      - "redis"

  api02:
    container_name: api02
    build: .docker/instancia
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/instancia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - "mysql-davenpay"
      - "redis"

  processador-jobs:
    container_name: processador-jobs
    build: .docker/instancia
    command: php artisan queue:listen
    volumes:
      - ./:/usr/share/nginx
      - .docker/instancia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - "mysql-davenpay"
      - "redis"

  nginx:
    build: .docker/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - .docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - default
    depends_on:
      - "api01"
      - "api02"

  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports: 
      - "8084:8080"
    environment:
      SWAGGER_JSON: /tmp/openapi.json
    volumes:
      - .docker/swagger:/tmp

networks:
  default:
    driver: bridge